### ISSUE TITLE
how to use user_data ?

### ISSUE THREAD

**Issue by lyc0221** [vultr/terraform-vultr-condor#24]
Can I use user_data instead of ssh_key_ids?

because user_data can help me quickly create the system account.

I try user_data, but it does not work.

**Comment by Oogy** [comment]
Hello @lyc0221, the instance user_data field is not currently supported for instances created by this module. Any instance configuration beyond what is done by this module will need to be done via external configuration management, or for example a [null_resource](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) with provisioners for each IP address in the module output `worker_public_ips` described [here](https://registry.terraform.io/modules/vultr/condor/vultr/latest?tab=outputs).
