### ISSUE TITLE
Missing required argument even during execution of `terraform plan`

### ISSUE THREAD

**Issue by yun14u** [vultr/terraform-vultr-condor#31]
**Describe the bug**
When executing `terraform plan -out main.tfplan`, terraform complains about missing required argument

**To Reproduce**
1. Execute `terraform -out main.tfplan` using the the following main.tf
module "condor" {
         source       = "vultr/condor/vultr"
         version      = "1.1.0"
         #
         cluster_vultr_api_key  = "BLAHBLAH"
   provisioner_public_key = chomp(file("/home/me/keypair/id_vultr.pub"))
   cluster_name               = "k8s"
   cluster_region             = "ewr"
   worker_count               = 2
   condor_network_subnet      = "10.10.10.0"
   condor_network_subnet_mask = 26
}

2. The following error appears
  
Error: Missing required argument
│
│ The argument "api_key" is required, but was not set.

According to https://registry.terraform.io/modules/vultr/condor/vultr/1.1.0?tab=inputs, the only required inputs are
cluster_vultr_api_key
provisioner_public_key

**Additional context**

**Comment by Oogy** [comment]
Hello @yun14u - while your module  configuraiton looks correct, the error appears to indicate you've not set the Vultr Terraform _provider_ `api_key` argument. Please do so as described [here](https://registry.terraform.io/providers/vultr/vultr/latest/docs).
