### ISSUE TITLE
[BUG] variable "enable_backups" 

### ISSUE THREAD

**Issue by yun14u** [vultr/terraform-vultr-condor#34]
**Describe the bug**
I encountered the following error when I performed `terraform apply`
module.condor.vultr_instance.workers[1]: Creating...
module.condor.vultr_instance.workers[0]: Creating...
module.condor.vultr_instance.controllers[0]: Creating...
╷
│ Error: error creating server: {"error":"Backups option must be either enabled or disabled.","status":400}
│
│   with module.condor.vultr_instance.controllers[0],
│   on .terraform/modules/condor/main.tf line 49, in resource "vultr_instance" "controllers":
│   49: resource "vultr_instance" "controllers" {
│
╵
╷
│ Error: error creating server: {"error":"Backups option must be either enabled or disabled.","status":400}
│
│   with module.condor.vultr_instance.workers[1],
│   on .terraform/modules/condor/main.tf line 94, in resource "vultr_instance" "workers":
│   94: resource "vultr_instance" "workers" {
│
╵
╷
│ Error: error creating server: {"error":"Backups option must be either enabled or disabled.","status":400}
│
│   with module.condor.vultr_instance.workers[0],
│   on .terraform/modules/condor/main.tf line 94, in resource "vultr_instance" "workers":
│   94: resource "vultr_instance" "workers" {
│
 

I'm suspecting that the following section of the variables.tf is incorrect
variable "enable_backups" {
  description = "Enable/disable instance backups"
  type        = bool
  default     = false
}

According to [this link](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance), "backups" argument expects "enabled or disabled", not boolean, "true or false".

**Comment by yun14u** [comment]
I noticed the file, variables.tf, has been modified.  I removed .terraform directory and performed `terraform init`.  When I rechecked the file, variables.tf, the bug is still there.  Any suggestion ?

**Comment by ddymko** [comment]
@yun14u Did you pull down the latest version that has these changes? v1.1.2

https://registry.terraform.io/modules/vultr/condor/vultr/latest


```hcl
module "condor" {
  source  = "vultr/condor/vultr"
  version = "1.1.2"
  # insert the 2 required variables here
}
```

**Comment by yun14u** [comment]
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ terraform plan -out main.tfplan
╷
│ Error: Invalid value for module argument
│
│   on main.tf line 18, in module "condor":
│   18:    enable_backups             = "disabled"
│
│ The given value is not suitable for child module variable "enable_backups" defined at
│ .terraform/modules/condor/variables.tf:37,1-26: a bool is required.

**Comment by ddymko** [comment]
@yun14u which version of condor are you running?

**Comment by yun14u** [comment]
my bad.  it's working.!
