### ISSUE TITLE
[BUG] issue during the creation of controller instance 

### ISSUE THREAD

**Issue by yun14u** [vultr/terraform-vultr-condor#38]
**Describe the bug**
I encountered the following error when I performed `terraform apply`
....
module.condor.vultr_private_network.condor_network: Creating...
module.condor.vultr_firewall_group.condor_firewall[0]: Creating...
module.condor.vultr_private_network.condor_network: Creation complete after 0s [id=81e47861-ca70-4ec1-9b1c-ff2ffcdabb0f]
module.condor.vultr_ssh_key.cluster_provisioner: Creation complete after 0s [id=fd4d4d0a-3276-41f9-a1b8-3c8c376acbae]
module.condor.vultr_firewall_group.condor_firewall[0]: Creation complete after 0s [id=7f49a818-fc77-476d-bee1-ca7185dacf8c]
module.condor.vultr_instance.workers[0]: Creating...
module.condor.vultr_instance.controllers[0]: Creating...
module.condor.vultr_instance.workers[1]: Creating...
module.condor.vultr_instance.workers[1]: Still creating... [10s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [10s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [10s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [20s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [20s elapsed]
module.condor.vultr_instance.workers[1]: Still creating... [20s elapsed]
module.condor.vultr_instance.workers[1]: Still creating... [30s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [30s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [30s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [40s elapsed]
module.condor.vultr_instance.workers[1]: Still creating... [40s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [40s elapsed]
module.condor.vultr_instance.workers[0]: Provisioning with 'file'...
module.condor.vultr_instance.controllers[0]: Provisioning with 'file'...
module.condor.vultr_instance.workers[1]: Provisioning with 'file'...
module.condor.vultr_instance.workers[1]: Still creating... [50s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [50s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [50s elapsed]
module.condor.vultr_instance.controllers[0]: Provisioning with 'remote-exec'...
module.condor.vultr_instance.controllers[0] (remote-exec): Connecting to remote host via SSH...
module.condor.vultr_instance.controllers[0] (remote-exec):   Host: 216.128.129.184
module.condor.vultr_instance.controllers[0] (remote-exec):   User: root
module.condor.vultr_instance.controllers[0] (remote-exec):   Password: false
module.condor.vultr_instance.controllers[0] (remote-exec):   Private key: false
module.condor.vultr_instance.controllers[0] (remote-exec):   Certificate: false
module.condor.vultr_instance.controllers[0] (remote-exec):   SSH Agent: true
module.condor.vultr_instance.controllers[0] (remote-exec):   Checking Host Key: false
module.condor.vultr_instance.controllers[0] (remote-exec):   Target Platform: unix
module.condor.vultr_instance.workers[1]: Still creating... [1m0s elapsed]
module.condor.vultr_instance.controllers[0]: Still creating... [1m0s elapsed]
module.condor.vultr_instance.workers[0]: Still creating... [1m0s elapsed]
module.condor.vultr_instance.controllers[0] (remote-exec): Connected!
module.condor.vultr_instance.controllers[0] (remote-exec): + apt -y update
module.condor.vultr_instance.controllers[0] (remote-exec):
module.condor.vultr_instance.controllers[0] (remote-exec): 0% [Working]
module.condor.vultr_instance.controllers[0] (remote-exec): Hit:1 http://security.debian.org/debian-security buster/updates InRelease
module.condor.vultr_instance.controllers[0] (remote-exec):
module.condor.vultr_instance.controllers[0] (remote-exec): 0% [Connecting to debian.map.fastlydns.
module.condor.vultr_instance.controllers[0] (remote-exec): Hit:2 http://deb.debian.org/debian buster InRelease
module.condor.vultr_instance.controllers[0] (remote-exec): Hit:3 http://deb.debian.org/debian buster-updates InRelease
module.condor.vultr_instance.controllers[0] (remote-exec):
module.condor.vultr_instance.controllers[0] (remote-exec): 0% [Working]
module.condor.vultr_instance.controllers[0] (remote-exec):
module.condor.vultr_instance.controllers[0] (remote-exec): 0% [Working]
module.condor.vultr_instance.controllers[0] (remote-exec):
module.condor.vultr_instance.controllers[0] (remote-exec): 0% [Working]
module.condor.vultr_instance.controllers[0] (remote-exec): 20% [Working]
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 57%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 57%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 95%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 95%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 98%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 98%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... 99%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading package lists... Done
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree... 50%
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree... 50%
module.condor.vultr_instance.controllers[0] (remote-exec): Building dependency tree
module.condor.vultr_instance.controllers[0] (remote-exec): Reading state information... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading state information... 0%
module.condor.vultr_instance.controllers[0] (remote-exec): Reading state information... Done
module.condor.vultr_instance.controllers[0] (remote-exec): 9 packages can be upgraded. Run 'apt list --upgradable' to see them.
module.condor.vultr_instance.controllers[0] (remote-exec): + apt -y install jq gnupg2
module.condor.vultr_instance.controllers[0] (remote-exec): E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
module.condor.vultr_instance.controllers[0] (remote-exec): E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

Something's definitely not right when the controller instance is being created.     Can you take a look into condor-provision.sh script  ?

**Comment by ddymko** [comment]
@yun14u Thanks for creating the ticket.

This is an issue with the debian image that we use to deploy condor with. We are working with the image team to resolve this issue.

**Comment by yun14u** [comment]
It works.
